name: 'Scan code and validate build'

on:
  push:
    branches: ['master', 'lib']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: '0 3 * * 1'

jobs:
  # Code quality analyzes wont work due to repo privacy.
  # CodeQuality:
  #   name: Analyze
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: read
  #     contents: read
  #     security-events: write
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       language: ['javascript', 'typescript']

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     # Initializes the CodeQL tools for scanning.
  #     - name: Initialize CodeQL
  #       uses: github/codeql-action/init@v1
  #       with:
  #         languages: ${{ matrix.language }}

  #     - name: Autobuild
  #       uses: github/codeql-action/autobuild@v1

  #     - name: Perform CodeQL Analysis
  #       uses: github/codeql-action/analyze@v1
  BuildValidation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn test
      - run: yarn build
  Audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm install
      - name: Run NPM audit and create PR with result
        uses: luisfontes19/npm-audit-action@v0.1.0
        with:
          project-path: '.'
          fix: true # To create pull requests with npm audit fix
          package-lock-only: false
          only: prod
          git-branch: fix/npm-audit-action
          force: true
          github-token: ${{ secrets.GITHUB_TOKEN }} # github token to create the pull request. Here you need to have a secret named TOKEN.
